-- SASP TEU Vehicle Seed Data
-- Run this AFTER schema.sql has created the table
-- 57 starter vehicles from the original CSV

INSERT INTO vehicles (id, vehicle, tier, responses, notes, image) VALUES
  ('t20-s', 'T20', 'S', '[{"tier": "S", "cars": ["Comet"]}]'::jsonb, '', 'vehicles/t20.png'),
  ('mf1-wb-s', 'MF1 wb', 'S', '[{"tier": "S", "cars": ["Dominator"]}, {"tier": "S+", "cars": ["Comet"]}]'::jsonb, 'Bez problemu stiha dominator', 'vehicles/mf1-wb.jpg'),
  ('itali-gto-s', 'Itali GTO', 'S', '[{"tier": "S", "cars": ["Dominator"]}, {"tier": "S+", "cars": ["Comet"]}]'::jsonb, 'Dominator stiha bez problemu', 'vehicles/itali-gto.png'),
  ('ignus-s', 'Ignus', 'S', '[{"tier": "S", "cars": ["Dominator"]}, {"tier": "S+", "cars": ["Comet"]}]'::jsonb, '', 'vehicles/ignus.png'),
  ('furia-s', 'Furia', 'S', '[{"tier": "S", "cars": ["Comet"]}]'::jsonb, '', 'vehicles/furia.png'),
  ('entity-mt-s', 'Entity MT', 'S', '[{"tier": "S", "cars": ["Vigero", "Gauntlet"]}, {"tier": "S+", "cars": ["Dominator", "Gauntlet"]}]'::jsonb, '(S+) Nechat Gauntlet primary, stíhá bez problému', 'vehicles/entity-mt.jpg'),
  ('emerus-s', 'Emerus', 'S', '[{"tier": "S", "cars": ["Dominator"]}, {"tier": "S+", "cars": ["Comet"]}]'::jsonb, '', 'vehicles/emerus.png'),
  ('corsita-s', 'Corsita', 'S', '[{"tier": "S", "cars": ["Vigero"]}, {"tier": "S+", "cars": ["Dominator"]}]'::jsonb, '', 'vehicles/corsita.png'),
  ('severo-s', 'Severo', 'S', '[{"tier": "S", "cars": ["Vigero"]}, {"tier": "S+", "cars": ["Comet"]}]'::jsonb, '(Full) Nestíhal jsem navázat ani s Dominátorem', 'vehicles/severo.jpg'),
  ('mf1-s', 'MF1', 'S', '[{"tier": "S", "cars": ["Dominator"]}, {"tier": "S+", "cars": ["Comet"]}]'::jsonb, '', 'vehicles/mf1.jpg'),
  ('grotti-turismo-3-s', 'Grotti Turismo 3', 'S', '[{"tier": "S", "cars": ["Vigero"]}, {"tier": "S+", "cars": ["Comet"]}]'::jsonb, '', 'vehicles/grotti-turismo-3.jpg'),
  ('turismor-s', 'TurismoR', 'S', '[{"tier": "S", "cars": ["Vigero"]}, {"tier": "S+", "cars": ["Comet"]}]'::jsonb, '', 'vehicles/turismor.png'),
  ('thrax-s', 'Thrax', 'S', '[{"tier": "S", "cars": ["Vigero"]}, {"tier": "S+", "cars": ["Comet"]}]'::jsonb, 'stock exceluje všetko veľký problém sa udržať vigerom', 'vehicles/thrax.png'),
  ('nerops-s', 'NeroPS', 'S', '[{"tier": "S", "cars": ["Dominator"]}, {"tier": "S+", "cars": ["Comet"]}]'::jsonb, '', 'vehicles/nerops.jpg'),
  ('italirsx-s', 'ItaliRSX', 'S', '[{"tier": "S", "cars": ["Dominator"]}, {"tier": "S+", "cars": ["Comet"]}]'::jsonb, 'Vigero stíhalo ako tak v meste ale na topspeed vôbec', 'vehicles/italirsx.png'),
  ('x80-proto-s', 'X80 Proto', 'S', '[{"tier": "S", "cars": ["Vigero"]}, {"tier": "S+", "cars": ["Comet"]}]'::jsonb, '', 'vehicles/x80-proto.png'),
  ('fmj-gte-s', 'FMJ GTE', 'S', '[{"tier": "S", "cars": ["Dominator"]}, {"tier": "S+", "cars": ["Comet"]}]'::jsonb, '', 'vehicles/fmj-gte.jpg'),
  ('auroras-s', 'AuroraS', 'S', '[{"tier": "S", "cars": ["Dominator"]}, {"tier": "S+", "cars": ["Comet"]}]'::jsonb, '', 'vehicles/auroras.jpg'),
  ('deveste-s', 'Deveste', 'S', '[{"tier": "S", "cars": ["Vigero"]}, {"tier": "S+", "cars": ["Dominator"]}]'::jsonb, '', 'vehicles/deveste.png'),
  ('torero-xo-s', 'Torero XO', 'S', '[{"tier": "S", "cars": ["Vigero"]}, {"tier": "S+", "cars": ["Comet"]}]'::jsonb, '', 'vehicles/torero-xo.jpg'),
  ('visione-s', 'Visione', 'S', '[{"tier": "S", "cars": ["Dominator"]}, {"tier": "S+", "cars": ["Comet"]}]'::jsonb, '', 'vehicles/visione.png'),
  ('zeno-s', 'Zeno', 'S', '[{"tier": "S", "cars": ["Dominator"]}, {"tier": "S+", "cars": ["Comet"]}]'::jsonb, 'Zatáčky - Maximálku stíhá Dominator, na zatáčky Comet', 'vehicles/zeno.png'),
  ('turismo-omaggio-s', 'Turismo Omaggio', 'S', '[{"tier": "S", "cars": ["Vigero", "STX"]}]'::jsonb, '', 'vehicles/turismo-omaggio.jpg'),
  ('osiris-r-s', 'Osiris R', 'S', '[{"tier": "S", "cars": ["Gauntlet", "Dominator"]}, {"tier": "S+", "cars": ["Dominator"]}]'::jsonb, 'Dominátor jediný stíhal poriadne', 'vehicles/osiris-r.jpg'),
  ('comet-s2r-s', 'Comet S2R', 'S', '[{"tier": "S", "cars": ["Gauntlet", "Dominator"]}, {"tier": "S+", "cars": ["Comet"]}]'::jsonb, 'S dominatorem se da stihat jen se musite snazit ve fullu pouze korveta', 'vehicles/comet-s2r.jpg'),
  ('tempesta-wb-s', 'Tempesta WB', 'S', '[{"tier": "S", "cars": ["Vigero"]}, {"tier": "S+", "cars": ["Vigero", "Dominator"]}]'::jsonb, 'Vigero dálnice nestíhá, město stíhá (S+)', 'vehicles/tempesta-wb.jpg'),
  ('prospero-s', 'Prospero', 'S', '[{"tier": "S", "cars": ["Dominator"]}, {"tier": "S+", "cars": ["Comet"]}]'::jsonb, 'V zatackach klouze, dobre zrychleni', 'vehicles/prospero.jpg'),
  ('solace-s', 'Solace', 'S', '[{"tier": "S", "cars": ["Vigero", "Dominator"]}]'::jsonb, 'Zatáčky, dobré zrychlení', 'vehicles/solace.jpg'),
  ('emerus-sb1-s', 'Emerus SB1', 'S', '[{"tier": "S", "cars": ["Vigero", "Dominator"]}, {"tier": "S+", "cars": ["Comet"]}]'::jsonb, '', 'vehicles/emerus-sb1.jpg'),
  ('811-sb2-s', '811 sb2', 'S', '[{"tier": "S", "cars": ["Vigero", "Gauntlet"]}, {"tier": "S+", "cars": ["Comet"]}]'::jsonb, 'Dobre zatacky mala maximalka', 'vehicles/811-sb2.jpg'),
  ('xa-21-a', 'XA-21', 'A', '[{"tier": "A", "cars": ["Vigero"]}]'::jsonb, 'Zatáčky / Na dálnici se dá stíhat v pohodě s Vigerem', 'vehicles/xa-21.png'),
  ('argento-a', 'Argento', 'A', '[{"tier": "A", "cars": ["Gauntlet"]}, {"tier": "A+", "cars": ["Vigero"]}]'::jsonb, 'Zatáčky/Dálnice - město Gauntlet - topspeed Vigero', 'vehicles/argento.jpg'),
  ('tigon-a', 'Tigon', 'A', '[{"tier": "A", "cars": ["Gauntlet", "Vigero"]}, {"tier": "A+", "cars": ["Dominator"]}]'::jsonb, 'Zatáčky, Dobre zrychleni', 'vehicles/tigon.png'),
  ('zorrusso-a', 'Zorrusso', 'A', '[{"tier": "A", "cars": ["Vigero"]}, {"tier": "A+", "cars": ["Dominator"]}]'::jsonb, 'Zatáčky, Dobre zrychleni', 'vehicles/zorrusso.png'),
  ('autarch-a', 'Autarch', 'A', '[{"tier": "A", "cars": ["Dominator"]}, {"tier": "A+", "cars": ["Dominator"]}]'::jsonb, 'Dálnice, Vigero vůbec nestíhalo, Dominátor ho dojížděl', 'vehicles/autarch.png'),
  ('calico-gtf-a', 'Calico GTF', 'A', '[{"tier": "A", "cars": ["Gauntlet"]}, {"tier": "A+", "cars": ["Dominator"]}]'::jsonb, 'Dálnice, Solidní zrychlení, gauntlet se vůbec nedržel', 'vehicles/calico-gtf.jpg'),
  ('zentorno-a', 'Zentorno', 'A', '[{"tier": "A", "cars": ["Vigero"]}]'::jsonb, 'Zatáčky/Dálnice - Menší chyba a dojíždí se dlouho', 'vehicles/zentorno.png'),
  ('tyrant-a', 'Tyrant', 'A', '[{"tier": "A", "cars": ["Dominator"]}, {"tier": "A+", "cars": ["Comet"]}]'::jsonb, 'Zátačky - Dominátor jediný stíhá, ovšem Tyrant lépe drží', 'vehicles/tyrant.png'),
  ('severo-a', 'Severo', 'A', '[{"tier": "A", "cars": ["Gauntlet", "Vigero"]}, {"tier": "A+", "cars": ["Gauntlet", "Vigero"]}]'::jsonb, 'Zátačky - Vigero akorát, zkusit Gauntlet', 'vehicles/severo.jpg'),
  ('jugular-a', 'Jugular', 'A', '[{"tier": "A", "cars": ["Gauntlet"]}, {"tier": "A+", "cars": ["Dominator", "Vigero"]}]'::jsonb, 'Zátačky - Bez problému gauntletem, opakovaně', 'vehicles/jugular.png'),
  ('supergts-a', 'SuperGTS', 'A', '[{"tier": "A", "cars": ["Vigero", "STX"]}]'::jsonb, 'Zatáčky - Stíháno s STX/, max 1 Vigero', 'vehicles/supergts.jpg'),
  ('itali-gtb-custom-a', 'Itali GTB Custom', 'A', '[{"tier": "A", "cars": ["Vigero"]}, {"tier": "A+", "cars": ["Dominator"]}]'::jsonb, 'Zátačky - Vigero problém navázat vizuál, jinak se drží', 'vehicles/itali-gtb-custom.jpg'),
  ('komoda-a', 'Komoda', 'A', '[{"tier": "A", "cars": ["Vigero"]}]'::jsonb, 'Dálnice - Chyba a je problém dohnat gap', 'vehicles/komoda.png'),
  ('audace-lampadati-a', 'Audace Lampadati', 'A', '[{"tier": "A", "cars": ["Vigero", "Dominator"]}]'::jsonb, 'Zátáčky / Zrychlení - město Vigero, dálnice Dominator', 'vehicles/audace-lampadati.jpg'),
  ('adder-a', 'Adder', 'A', '[{"tier": "A", "cars": ["STX"]}, {"tier": "A+", "cars": ["Vigero", "Dominator"]}]'::jsonb, 'Stock STX stačí - Full - vigero nestačí', 'vehicles/adder.png'),
  ('penetrator-a', 'Penetrator', 'A', '[{"tier": "A", "cars": ["Vigero", "STX"]}, {"tier": "A+", "cars": ["Vigero", "Dominator"]}]'::jsonb, 'STX se dá (dokud mel lokator, tak jezdil na omezovac)', 'vehicles/penetrator.png'),
  ('estancia-a', 'Estancia', 'A', '[{"tier": "A", "cars": ["STX", "Vigero"]}]'::jsonb, 'Zatáčky - Vigero do zatáček, maximalkou stačí STX', 'vehicles/estancia.jpg'),
  ('coquette-d5-a', 'Coquette D5', 'A', '[{"tier": "A", "cars": ["STX"]}, {"tier": "A+", "cars": ["Vigero"]}]'::jsonb, 'Zatáčky - stačí STX // maximálka A+ vigero', 'vehicles/coquette-d5.jpg'),
  ('osiris-a', 'Osiris', 'A', '[{"tier": "A", "cars": ["Vigero"]}]'::jsonb, 'Zatáčky - Vigero nejspíš', 'vehicles/osiris.png'),
  ('luiva-a', 'Luiva', 'A', '[{"tier": "A", "cars": ["Gauntlet"]}, {"tier": "A+", "cars": ["Dominator"]}]'::jsonb, 'Zátačky a rýchlosť, v plusku nestíha žiadne PD auto( 160mph+)', 'vehicles/luiva.jpg'),
  ('banshee-gts-a', 'Banshee GTS', 'A', '[{"tier": "A", "cars": ["Vigero"]}, {"tier": "A+", "cars": ["Dominator"]}]'::jsonb, 'Rýchlosť vigero solo nestíhalo ho na maximálku zrýchlenie', 'vehicles/banshee-gts.jpg'),
  ('jugular-st-a', 'Jugular ST', 'A', '[{"tier": "A", "cars": ["Vigero"]}, {"tier": "A+", "cars": ["Dominator"]}]'::jsonb, 'Vigero nestíhalo na dálnici', 'vehicles/jugular-st.jpg'),
  ('celeste-a', 'Celeste', 'A', '[{"tier": "A", "cars": ["Vigero"]}, {"tier": "A+", "cars": ["Dominator"]}]'::jsonb, 'Vigero stačilo na stock', 'vehicles/celeste.jpg'),
  ('jester-rr-wb-a', 'Jester RR WB', 'A', '[{"tier": "A", "cars": ["STX"]}]'::jsonb, 'zátačky', 'vehicles/jester-rr-wb.jpg'),
  ('sultan-rs-classic-a', 'Sultan RS Classic', 'A', '[{"tier": "A", "cars": ["STX"]}, {"tier": "A+", "cars": ["Vigero"]}]'::jsonb, 'zátačky', 'vehicles/sultan-rs-classic.png'),
  ('sultan-rsx-a', 'Sultan RSx', 'A', '[{"tier": "A", "cars": ["Vigero", "Gauntlet"]}, {"tier": "A+", "cars": ["Dominator", "Gauntlet"]}]'::jsonb, 'Neklouze je lepsi na tahle zatacky, zrychleni dobry', 'vehicles/sultan-rsx.png'),
  ('gp1-a', 'GP1', 'A', '[{"tier": "A", "cars": ["Vigero", "Gauntlet"]}]'::jsonb, 'Zatáčky, dobré zrychlení', 'vehicles/gp1.png')
ON CONFLICT (id) DO NOTHING;

-- Done. You should now see 57 vehicles in your vehicles table.